### ISSUE TITLE
migreazy doesn't load in Ruby 2

### ISSUE THREAD

**Issue by Peeja** [fhwang/migreazy#3]
Getting `cannot load such file -- config/boot (LoadError)`. I think Ruby 2 changed the load path; was `.` previously in the load path by default? `require 'config/boot'` doesn't seem to cut it anymore.

**Comment by fhwang** [comment]
Yeah it looks like there was a pathing error with Rails 3 (and 4 presumably?). I released a fix in Migreazy 2.0, can you install that and give it a try?
