### ISSUE TITLE
`unpack_object_header_gently': undefined method `>>' for "x":String (NoMethodError)

### ISSUE THREAD

**Issue by malachaifrazier** [fhwang/migreazy#4]
Noted this when running 'migreazy find xxxxxx'

/Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/internal/loose.rb:108:in `unpack_object_header_gently': undefined method`>>' for "x":String (NoMethodError)
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/internal/loose.rb:56:in `get_raw_object'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/internal/loose.rb:32:in`[]'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:84:in `block in get_raw_object_by_sha1'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:83:in`each'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:83:in `get_raw_object_by_sha1'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:334:in`walk_log'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:287:in `log'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:306:in`rev_list'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby.rb:70:in `block in rev_list'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby.rb:211:in`block in try_run'
    from /Users/malachaifrazier/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby.rb:210:in`try_run'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/git-ruby.rb:70:in `rev_list'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/commit.rb:120:in`find_all'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/commit.rb:93:in `lazy_source'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/grit-2.5.0/lib/grit/lazy.rb:31:in`block (2 levels) in lazy_reader'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/migreazy-2.0.2/lib/migreazy.rb:90:in `block in run'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/migreazy-2.0.2/lib/migreazy.rb:89:in`select'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/migreazy-2.0.2/lib/migreazy.rb:89:in `run'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/gems/migreazy-2.0.2/bin/migreazy:18:in`<top (required)>'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/bin/migreazy:23:in `load'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/bin/migreazy:23:in`<main>'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
    from /Users/malachaifrazier/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in`<main>'

**Comment by fhwang** [comment]
Thanks for the report. Things have been fairly hectic for me but hopefully I'll be able to look into this soon.

**Comment by malachaifrazier** [comment]
Ditto! I've been meaning to attack this...but work

**Comment by fhwang** [comment]
Looks like the underlying library Grit is no longer being maintained, so the fix was to move it to Rugged instead. Give it a try now.
